### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by piskunqa** [hyugogirubato/cbz#13]
remove please @cache from file pack function (caching objects of 50-200 megabytes is not a good idea)
if you still need a cache, then add a constructor that will remove this object from cache when deleting a class object from memory

and fix space in " . jpg"  format

**Comment by hyugogirubato** [comment]
The use of cache for this function is an experiment that I wanted to carry out. Obviously it is not relevant in this context, so I removed it according to your advice.

Besides, thank you for pointing out the typo for `.jpg` because I hadn't noticed it.

I published a new version (3.3.3) correcting certain problems like yours. Enjoy!
